FROM node:22-alpine

WORKDIR /apps

ARG APP_NAME
ENV APP_NAME=${APP_NAME}

COPY package.json package-lock.json ./

RUN npm install --include=optional --include=dev

COPY . .

RUN if [ "$APP_NAME" = "auth-service" ]; then \
      npx prisma generate --schema=apps/auth-service/prisma/schema.prisma; \
    elif [ "$APP_NAME" = "user-service" ]; then \
      npx prisma generate --schema=apps/user-service/prisma/schema.prisma; \
    elif [ "$APP_NAME" = "social-service" ]; then \
      npx prisma generate --schema=apps/social-service/prisma/schema.prisma; \
    fi

RUN npx nx build ${APP_NAME}

EXPOSE 3000

CMD ["sh", "-c", "node apps/${APP_NAME}/dist/main.js"]